### ISSUE TITLE
Raytracing on Metal 

### ISSUE THREAD

**Issue by nejurgis** [KHN190/the-biography#1]
Heya, Thanks for this tutorial and the source, you're a talented teacher! I tried running this project on my Mac and I'm getting an error: 
`RayTrace.compute: Kernel at index (0) is invalid`

I Suppose it has to do with the fact that there's no DirectX support on Mac? Do you know if there's any changes that could be done to the code to be able to run this compute shader on Metal/MacOS?

**Comment by KHN190** [comment]
If you open Unity editor you'll see a compile error at compute shader:

> Shader error in 'RayTrace': syntax error: unexpected token '#' at kernel Main at /the/path/to/the-biography/Assets/RayTrace.cginc(43) (on metal)

The line 43 says:

```
hit.distance = 1.#INF;
```

, which sets default ray hit distance to infinity and later is used to store closest ray hit distance. 

And you see the error "kernel is invalid" is caused by it. I think it's a Unity shader compile bug because as far as I know it compiles well on Linux, and it is a valid syntax in HLSL. The solution would be manually set the value to a very large number.

A search showed some people could do:

```hlsl
#define FLOAT_MAX 1.0f / 0.0f
```

and plug it in.

**Comment by nejurgis** [comment]
Thanks for your help, changing the value from hit.distance = 1.#INF; to a FLOAT_MAX indeed helped to show the tiling background, however the actual refractive object isn't visible. Getting an error about the floating point division by zero? 
<img width="766" alt="Screen Shot 2021-03-06 at 22 13 37" src="https://user-images.githubusercontent.com/9300426/110220941-48cf3f00-7ec9-11eb-8a27-89799e68d9f9.png">

**Comment by KHN190** [comment]
Ummmm...You could set the value to `FLOAT_MAX = 10000.0f`, that should work in this scenario.

And in fact it has another problem above the line "Metal does not support buffer size query", which I just found in the [Unity doc](https://docs.unity3d.com/Manual/class-ComputeShader.html):

```
// Get the dimensions of the RenderTexture
uint width, height;
Result.GetDimensions(width, height); // not supported on Metal
```

In that way, you could pass in the width and height from `RayTrace.cs`, which is defined here:

```csharp
RenderTexture init = new RenderTexture(Screen.width, Screen.height, 0, // here
    RenderTextureFormat.ARGBFloat, RenderTextureReadWrite.Linear);
```

I only tested the shader on Linux since I have an external GPU on it, if you fixed the issues, could you also create a PR?

**Comment by nejurgis** [comment]
Thanks for your answer, how would you actually pass the Render Texture from C# script to the Compute Shader? Couldn't figure it out

**Comment by KHN190** [comment]
> Thanks for your answer, how would you actually pass the Render Texture from C# script to the Compute Shader? Couldn't figure it out

In the `RayTrace.cs`, you have the same data structure both in C# and compute shader, and you register their mirror relationship using `SetTexture`, `SetBuffer` or `SetFloat` (which you'd like to send a single float) etc. And when you call `Dispatch` on compute, there's where you actually send the data to GPU.

[Unity doc](https://docs.unity3d.com/ScriptReference/ComputeShader.html) is a good start! The `SetInt` is the thing you need. Just define the int both in C# and compute, in `Render` function data will be sent to GPU as in. Since `OnRenderImage` is called per frame, data is updated at frame rate.

```csharp
private void OnRenderImage(RenderTexture source, RenderTexture destination)
{
    Render(destination);
}

private void Render(RenderTexture destination)
{
    // ...
    // same thing for integers
    compute.SetFloat("_Time", Time.time * 0.18f);
    // ...
    // send data to GPU
    compute.Dispatch(0, threadGroupsX, threadGroupsY, 1);
    // ...
}
```

You can read the code this project used [here](https://github.com/KHN190/the-biography/blob/master/Assets/RayTrace.cs#L58).

**Comment by nejurgis** [comment]
I see, so if I understand you correctly then this would be the way to go? 

```
    private void Render(RenderTexture destination)
    {
        // Make sure we have a current render target
        InitRenderTexture();

        // Set the target and dispatch the compute shader
        compute.SetTexture(0, "Result", target);
        compute.SetBuffer(0, "_Spheres", buffer);
        compute.SetMatrix("_CameraToWorld", Camera.main.cameraToWorldMatrix);
    	compute.SetMatrix("_CameraInverseProjection", Camera.main.projectionMatrix.inverse);
        compute.SetFloat("_Time", Time.time * 0.18f);
        compute.SetFloat("_ScreenWidth", Screen.width);
        compute.SetFloat("_ScreenHeight", Screen.height);
        int threadGroupsX = Mathf.CeilToInt(Screen.width / 8.0f);
        int threadGroupsY = Mathf.CeilToInt(Screen.height / 8.0f);
        compute.Dispatch(0, threadGroupsX, threadGroupsY, 1);

        // Blit the result texture to the screen
        Graphics.Blit(target, destination);
    }
```

and then the Compute Shader Side:
```
    // Input
    float4x4 _CameraToWorld;
    float4x4 _CameraInverseProjection;
    StructuredBuffer<Sphere> _Spheres;
    float _Time;
    float _ScreenWidth;
    float _ScreenHeight;

void Main (uint3 id : SV_DispatchThreadID)
{
    // Transform pixel to [-1,1] range
    float2 uv = float2((id.xy + 0.5) / float2(_ScreenWidth, _ScreenHeight) * 2.0f - 1.0f);

```

There is however another problem:
 `_Spheres.GetDimensions(nSpheres, stride);` 
How could I pass the data in here?

**Comment by KHN190** [comment]
Screen width is integer! You should pass in as int.

Since you know the number of spheres in C#, you can pass in that one, too.

For `stride`, it's the size of each sphere in bytes: https://docs.unity3d.com/ScriptReference/ComputeBuffer.html

A float is 4 bytes, and a sphere contains 3 `Vector3` + 1 `float` = 10 `float`, that is 40. I calculated it on [this line](https://github.com/KHN190/the-biography/blob/master/Assets/RayTrace.cs#L30)

 ```csharp
// set sphere data size in bytes
buffer = new ComputeBuffer(spheres.Count, 40);
```

However, after reading the code, I found `stride` is declared but not actually used in it. So you could just pass in `nSpheres`.
